<a href="https://colab.research.google.com/github/riyabhatta9818/games/blob/main/sudoku_proj2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
grid=[[8,0,4,0,2,3,0,0,1],
      [0,3,0,8,0,4,2,0,0],
      [0,0,7,0,9,0,0,0,0],
      [0,0,0,4,1,0,9,0,0],
      [3,4,0,7,8,0,6,1,0],
      [0,0,0,9,3,6,5,4,8],
      [0,0,0,0,0,8,0,0,0],
      [0,7,1,0,0,0,0,0,6],
      [9,8,5,0,0,0,4,0,0]]

In [3]:
print(np.matrix(grid))

[[8 0 4 0 2 3 0 0 1]
 [0 3 0 8 0 4 2 0 0]
 [0 0 7 0 9 0 0 0 0]
 [0 0 0 4 1 0 9 0 0]
 [3 4 0 7 8 0 6 1 0]
 [0 0 0 9 3 6 5 4 8]
 [0 0 0 0 0 8 0 0 0]
 [0 7 1 0 0 0 0 0 6]
 [9 8 5 0 0 0 4 0 0]]


In [9]:
def possible(row,column,number):
# now we need to check if the same number is been repeating in the row,column or in box
  global grid
# if the number is been repeated in the same row or column then the same number should be removed
# is the number been repeated in the row
  for i in range(0,9):
      if grid [row] [i] == number:
          return False
# is the number been repeated in the column
  for i in range(0,9):
      if grid [i] [column] == number:
        return False
# is the number been repeated in the square
# there are 3 row and 3 column in one square box
# for eg : if the given column is 6 then 6//3*3 , the outcome is 6
# ... so if the outcome is 6 and i = 1 , then the outcome would be 7
# so the number 7 is not been reapeated in the given column then it should return true otherwise false
  x0 = (column//3) * 3
  y0 = (row//3) * 3
  for i in range(0,3):
      for j in range(0,3):
          if grid [y0+i][x0+j] == number:
              return False
  return True
# but till now python doesnot know the exact correct ans in the a specific row , column , square


In [10]:
def solve():
    global grid
# now we are going to check if the given field is empty or not because if it not empty then we donot want it to fill that field
    for row in range(0,9):
        for column in range(0,9):
# if the row or column is 0 whih represents an empty field then it should continue to solve
            if grid [row][column]==0:
                for number in range(1,10):
                    if possible (row,column,number):
                        grid [row][column] = number
                        solve()
                        grid [row][column] = 0

                return

    print(np.matrix(grid))
    input('more possible solution?')

In [11]:
solve()

[[8 9 4 5 2 3 7 6 1]
 [1 3 6 8 7 4 2 9 5]
 [5 2 7 6 9 1 3 8 4]
 [6 5 8 4 1 2 9 3 7]
 [3 4 9 7 8 5 6 1 2]
 [7 1 2 9 3 6 5 4 8]
 [4 6 3 2 5 8 1 7 9]
 [2 7 1 3 4 9 8 5 6]
 [9 8 5 1 6 7 4 2 3]]
more possible solution?


In [12]:
grid=[[8,0,4,0,2,3,0,0,1],
      [0,3,0,8,0,4,2,0,0],
      [0,0,7,0,9,0,0,0,0],
      [0,0,0,4,1,0,9,0,0],
      [3,4,0,7,8,0,6,1,0],
      [0,0,0,9,3,6,5,4,8],
      [0,0,0,0,0,8,0,0,0],
      [0,7,1,0,0,0,0,0,6],
      [9,8,5,0,0,0,4,0,3]]

In [13]:
solve()

[[8 9 4 5 2 3 7 6 1]
 [1 3 6 8 7 4 2 9 5]
 [5 2 7 6 9 1 3 8 4]
 [6 5 8 4 1 2 9 3 7]
 [3 4 9 7 8 5 6 1 2]
 [7 1 2 9 3 6 5 4 8]
 [4 6 3 2 5 8 1 7 9]
 [2 7 1 3 4 9 8 5 6]
 [9 8 5 1 6 7 4 2 3]]
more possible solution?
